"""Initial schema

Revision ID: 0d02047fefb7
Revises: 
Create Date: 2026-08-05 12:47:50.156397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d02047fefb7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servers',
    sa.Column('server_id', sa.String(length=100), nullable=False),
    sa.Column('server_name', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.String(length=100), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=False),
    sa.Column('verification_level', sa.Integer(), nullable=False),
    sa.Column('default_message_notifications', sa.Integer(), nullable=False),
    sa.Column('explicit_content_filter', sa.Integer(), nullable=False),
    sa.Column('system_channel_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('server_id')
    )
    op.create_table('channels',
    sa.Column('channel_id', sa.String(length=100), nullable=False),
    sa.Column('server_id', sa.String(length=100), nullable=False),
    sa.Column('channel_name', sa.String(length=255), nullable=False),
    sa.Column('channel_type', sa.String(length=20), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('nsfw', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_per_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.server_id'], ),
    sa.PrimaryKeyConstraint('channel_id')
    )
    op.create_table('daily_stats',
    sa.Column('server_id', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_messages', sa.Integer(), nullable=False),
    sa.Column('new_members', sa.Integer(), nullable=False),
    sa.Column('total_members', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('is_weekend', sa.Boolean(), nullable=False),
    sa.Column('active_members', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.server_id'], ),
    sa.PrimaryKeyConstraint('server_id', 'date')
    )
    op.create_table('members',
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('server_id', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('discriminator', sa.String(length=4), nullable=False),
    sa.Column('avatar_hash', sa.String(length=255), nullable=True),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('join_date', sa.DateTime(), nullable=False),
    sa.Column('last_active', sa.DateTime(), nullable=False),
    sa.Column('roles', sa.String(length=255), nullable=True),
    sa.Column('messages_sent', sa.Integer(), nullable=False),
    sa.Column('voice_minutes', sa.Integer(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.server_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'server_id')
    )
    op.create_table('channel_daily_stats',
    sa.Column('channel_id', sa.String(length=100), nullable=False),
    sa.Column('server_id', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('messages_count', sa.Integer(), nullable=False),
    sa.Column('active_users', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.channel_id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['servers.server_id'], ),
    sa.PrimaryKeyConstraint('channel_id', 'server_id', 'date')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.String(length=100), nullable=False),
    sa.Column('server_id', sa.String(length=100), nullable=False),
    sa.Column('channel_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('has_attachment', sa.Boolean(), nullable=False),
    sa.Column('has_embed', sa.Boolean(), nullable=False),
    sa.Column('reaction_count', sa.Integer(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.channel_id'], ),
    sa.ForeignKeyConstraint(['server_id', 'user_id'], ['members.server_id', 'members.user_id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['servers.server_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_messages_channel_id'), 'messages', ['channel_id'], unique=False)
    op.create_index(op.f('ix_messages_server_id'), 'messages', ['server_id'], unique=False)
    op.create_index(op.f('ix_messages_timestamp'), 'messages', ['timestamp'], unique=False)
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_timestamp'), table_name='messages')
    op.drop_index(op.f('ix_messages_server_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_channel_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('channel_daily_stats')
    op.drop_table('members')
    op.drop_table('daily_stats')
    op.drop_table('channels')
    op.drop_table('servers')
    # ### end Alembic commands ###
